
F(Harmonics1, HRM1, Source, 0, 0, 0, "VCO 1 Cos Blend", SmartGrid::Color::Red, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(Harmonics2, HRM2, Source, 0, 1, 0, "VCO 2 Cos Blend", SmartGrid::Color::Red, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(VPSV1, V1, Source, 1, 0, 1.0 / 8.0, "VCO 1 V", SmartGrid::Color::Red, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(VPSV2, V2, Source, 1, 1, 1.0 / 8.0, "VCO 2 V", SmartGrid::Color::Red, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(VPSD1, D1, Source, 2, 0, 0.5, "VCO 1 D", SmartGrid::Color::Red, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(VPSD2, D2, Source, 2, 1, 0.5, "VCO 2 D", SmartGrid::Color::Red, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(PhaseMod1, PM1, Source, 3, 0, 0, "VCO 2->1 PM", SmartGrid::Color::Red, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(PhaseMod2, PM2, Source, 3, 1, 0, "VCO 1->2 PM", SmartGrid::Color::Red, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(OscillatorMix, MIX, Source, 0, 2, 0, "VCO 1 Fade", SmartGrid::Color::Yellow, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(PMMainSVFCutoff, PMFC, Source, 0, 0, 0.5, "PM SVF Cutoff", SmartGrid::Color::Red, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(PMMainSVFResonance, PMFR, Source, 1, 0, 0.3, "PM SVF Resonance", SmartGrid::Color::Red, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(PMMainSVFMorph, PMFM, Source, 2, 0, 0.5, "PM SVF Morph", SmartGrid::Color::Red, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(PMSampleRateReduction, PMSR, Source, 3, 0, 0.5, "PM Sample Rate", SmartGrid::Color::Red, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(PMAHDAttack, PMAA, Source, 0, 1, 0, "PM AHD Attack", SmartGrid::Color::Red, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(PMAHDHold, PMAH, Source, 1, 1, 0.5, "PM AHD Hold", SmartGrid::Color::Red, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(PMAHDDecay, PMAD, Source, 2, 1, 0.3, "PM AHD Decay", SmartGrid::Color::Red, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(PMAmplitude, PMAP, Source, 3, 1, 1, "PM Amplitude", SmartGrid::Color::Red, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(PMCombFeedback, PMCB, Source, 0, 2, 0.5, "PM Comb Feedback", SmartGrid::Color::Yellow, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(PMCombDampenCutoff, PMDC, Source, 0, 3, 0.5, "PM Comb Dampen Cutoff", SmartGrid::Color::Yellow, MachineFlags::x_physicalModelingOnly, MachineFlags::x_all)
F(FilterDrive, DRV, Source, 2, 2, 0, "Saturation", SmartGrid::Color::Green, MachineFlags::x_all, MachineFlags::x_all)
F(BitReduction, BR, Source, 1, 2, 0, "Bit Reduction", SmartGrid::Color::Green, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(SampleRateReduction, SRR, Source, 3, 2, 0, "Sample Rate Reduction", SmartGrid::Color::Green, MachineFlags::x_all, MachineFlags::x_all)
F(PitchOffset, PIT, Source, 0, 3, 0, "VCO 2 Pitch Offset", SmartGrid::Color::Yellow, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(OscillatorDetune, DET, Source, 1, 3, 0, "Pitch Drift", SmartGrid::Color::Yellow, MachineFlags::x_dualWaveShapingVCOOnly, MachineFlags::x_all)
F(SubOscillator, SUB, Source, 3, 3, 0, "Sub Oscillator", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(HPCutoff, HPF, FilterAndAmp, 0, 1, 0, "HP Cutoff", SmartGrid::Color::Green, MachineFlags::x_all, MachineFlags::x_all)
F(HPResonance, HPR, FilterAndAmp, 1, 1, 0, "HP Resonance", SmartGrid::Color::Green, MachineFlags::x_all, MachineFlags::x_all)
F(LPCutoff, LPF, FilterAndAmp, 2, 1, 1, "LP Cutoff", SmartGrid::Color::Green, MachineFlags::x_all, MachineFlags::x_all)
F(LPResonance, LPR, FilterAndAmp, 3, 1, 0, "LP Resonance", SmartGrid::Color::Green, MachineFlags::x_all, MachineFlags::x_all)
F(ModAHDAttack, FAD, FilterAndAmp, 0, 0, 0, "Mod AHD Attack", ADSRColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(ModAHDHold, FHO, FilterAndAmp, 1, 0, 0.5, "Mod AHD Hold", ADSRColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(ModAHDDecay, FDC, FilterAndAmp, 2, 0, 0.2, "Mod AHD Decay", ADSRColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(ModAmplitude, FAMP, FilterAndAmp, 3, 0, 1, "Mod Amplitude", ADSRColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(AmpAHDAttack, AAD, FilterAndAmp, 0, 2, 0, "Amp AHD Attack", ADSRColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(AmpAHDHold, AHO, FilterAndAmp, 1, 2, 0.5, "Amp AHD Hold", ADSRColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(AmpAHDDecay, ADC, FilterAndAmp, 2, 2, 0.3, "Amp AHD Decay", ADSRColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(AmpAmplitude, AAMP, FilterAndAmp, 3, 2, 1, "Amp Amplitude", ADSRColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(AmpGain, GAIN, FilterAndAmp, 0, 3, 1, "Amp Gain", SmartGrid::Color::Green, MachineFlags::x_all, MachineFlags::x_all)
F(DelaySend, DLS, FilterAndAmp, 1, 3, 0, "Delay Send", SmartGrid::Color::Green, MachineFlags::x_all, MachineFlags::x_all)
F(ReverbSend, RVS, FilterAndAmp, 2, 3, 0, "Reverb Send", SmartGrid::Color::Green, MachineFlags::x_all, MachineFlags::x_all)
F(PanRadius, RAD, PanningAndSequencing, 0, 0, 1, "Pan Radius", SmartGrid::Color::Orange, MachineFlags::x_all, MachineFlags::x_all)
F(PanPhaseShift, PPS, PanningAndSequencing, 1, 0, 0, "Pan Phase Shift", SmartGrid::Color::Orange, MachineFlags::x_all, MachineFlags::x_all)
F(PanMultX, PMX, PanningAndSequencing, 2, 0, 0, "Pan Mult X", SmartGrid::Color::Orange, MachineFlags::x_all, MachineFlags::x_all)
F(PanMultY, PMY, PanningAndSequencing, 3, 0, 0, "Pan Mult Y", SmartGrid::Color::Orange, MachineFlags::x_all, MachineFlags::x_all)
F(PanCenterX, PCX, PanningAndSequencing, 0, 1, 0.5, "Pan Center X", SmartGrid::Color::Orange, MachineFlags::x_all, MachineFlags::x_all)
F(PanCenterY, PCY, PanningAndSequencing, 1, 1, 0.5, "Pan Center Y", SmartGrid::Color::Orange, MachineFlags::x_all, MachineFlags::x_all)
F(Portamento, PRT, PanningAndSequencing, 3, 1, 0, "Portamento", SmartGrid::Color::Orange, MachineFlags::x_all, MachineFlags::x_all)
F(SeqZoneHeight, SZH, PanningAndSequencing, 0, 2, 0.25, "Sequencer Zone Height", SmartGrid::Color::Orange.Interpolate(SmartGrid::Color::Blue, 0.5), MachineFlags::x_all, MachineFlags::x_all)
F(SeqZoneOverlap, SZO, PanningAndSequencing, 1, 2, 0.5, "Sequencer Zone Overlap", SmartGrid::Color::Orange.Interpolate(SmartGrid::Color::Blue, 0.5), MachineFlags::x_all, MachineFlags::x_all)
F(SeqOffset, SOFF, PanningAndSequencing, 0, 3, 0, "Sequencer Offset", SmartGrid::Color::Orange.Interpolate(SmartGrid::Color::Blue, 0.5), MachineFlags::x_all, MachineFlags::x_all)
F(SeqInterval, SINT, PanningAndSequencing, 1, 3, 0, "Sequencer Interval", SmartGrid::Color::Orange.Interpolate(SmartGrid::Color::Blue, 0.5), MachineFlags::x_all, MachineFlags::x_all)
F(SeqPageInterval, SPGI, PanningAndSequencing, 2, 3, 0, "Sequencer Page Interval", SmartGrid::Color::Orange.Interpolate(SmartGrid::Color::Blue, 0.5), MachineFlags::x_all, MachineFlags::x_all)
F(LFO1Skew, L1SK, VoiceLFOs, 0, 0, 0.5, "LFO 1 Skew", LFOColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(LFO1Mult, L1MU, VoiceLFOs, 1, 0, 0, "LFO 1 Mult", LFOColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(LFO1Shape, L1SH, VoiceLFOs, 2, 0, 0.5, "LFO 1 Shape", LFOColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(LFO1Amplitude, L1AM, VoiceLFOs, 3, 0, 1.0, "LFO 1 Amplitude", LFOColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(LFO1Center, L1CT, VoiceLFOs, 0, 1, 0.75, "LFO 1 Center", LFOColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(LFO1Slope, L1SL, VoiceLFOs, 1, 1, 0, "LFO 1 Slope", LFOColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(LFO1PhaseShift, L1PS, VoiceLFOs, 2, 1, 1.0, "LFO 1 Phase Shift", LFOColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(LFO1SampleAndHold, L1SA, VoiceLFOs, 3, 1, 0, "LFO 1 Sample And Hold", LFOColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(LFO2Skew, L2SK, VoiceLFOs, 0, 2, 0.5, "LFO 2 Skew", LFOColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(LFO2Mult, L2MU, VoiceLFOs, 1, 2, 0, "LFO 2 Mult", LFOColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(LFO2Shape, L2SH, VoiceLFOs, 2, 2, 0.5, "LFO 2 Shape", LFOColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(LFO2Amplitude, L2AM, VoiceLFOs, 3, 2, 1.0, "LFO 2 Amplitude", LFOColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(LFO2Center, L2CT, VoiceLFOs, 0, 3, 0.25, "LFO 2 Center", LFOColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(LFO2Slope, L2SL, VoiceLFOs, 1, 3, 0, "LFO 2 Slope", LFOColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(LFO2PhaseShift, L2PS, VoiceLFOs, 2, 3, 1.0, "LFO 2 Phase Shift", LFOColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(LFO2SampleAndHold, L2SA, VoiceLFOs, 3, 3, 0, "LFO 2 Sample And Hold", LFOColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(DelayTime, DLT, Delay, 0, 0, 0.75, "Delay Time", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(DelayTimeFactor, DLF, Delay, 1, 0, 0.75, "Delay Time Factor", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(DelayFeedback, DLFB, Delay, 3, 0, 0.75, "Delay Feedback", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(DelayDampBase, DDB, Delay, 0, 1, 0.4, "Delay Damp Base", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(DelayDampWidth, DDW, Delay, 1, 1, 0.3, "Delay Damp Width", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(ResynthSlewUp, RSU, Delay, 2, 1, 0.0, "Resynth Slew Up", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(DelayReverbSend, DRS, Delay, 3, 1, 0, "Reverb Send", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(DelayWiden, DLW, Delay, 0, 2, 0, "Delay Widen", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(DelayRotate, DLR, Delay, 1, 2, 0.25, "Delay Rotate", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(ResynthUnison, RUN, Delay, 2, 2, 0.0, "Resynth Unison", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(ResynthShiftFade, RSF, Delay, 1, 3, 0.0, "Resynth Shift Fade", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(ResynthShiftInterval, RSI, Delay, 2, 3, 1.0, "Resynth Shift Interval", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(DelayReturn, DLRR, Delay, 3, 3, 1.0, "Delay Return", SmartGrid::Color::Pink, MachineFlags::x_all, MachineFlags::x_all)
F(ReverbTime, RVT, Reverb, 0, 0, 0.5, "Reverb Time", SmartGrid::Color::Fuscia, MachineFlags::x_all, MachineFlags::x_all)
F(ReverbFeedback, RVF, Reverb, 3, 0, 0.75, "Reverb Feedback", SmartGrid::Color::Fuscia, MachineFlags::x_all, MachineFlags::x_all)
F(ReverbDampBase, RDB, Reverb, 0, 1, 0.3, "Reverb Damp Base", SmartGrid::Color::Fuscia, MachineFlags::x_all, MachineFlags::x_all)
F(ReverbDampWidth, RDW, Reverb, 1, 1, 0.5, "Reverb Damp Width", SmartGrid::Color::Fuscia, MachineFlags::x_all, MachineFlags::x_all)
F(ReverbDelaySend, RDS, Reverb, 3, 1, 0, "Delay Send", SmartGrid::Color::Fuscia, MachineFlags::x_all, MachineFlags::x_all)
F(DelayModSpeed, DMS, Reverb, 1, 2, 0.1, "Delay Mod Speed", QuadratureColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(DelayModPhaseShift, DMPS, Reverb, 2, 2, 1.0, "Delay Mod Phase Shift", QuadratureColor(0), MachineFlags::x_all, MachineFlags::x_all)
F(ReverbModDepth, RMD, Reverb, 0, 3, 0, "Reverb Mod Depth", SmartGrid::Color::Fuscia, MachineFlags::x_all, MachineFlags::x_all)
F(ReverbModSpeed, RMS, Reverb, 1, 3, 0.1, "Reverb Mod Speed", QuadratureColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(ReverbModPhaseShift, RMPS, Reverb, 2, 3, 1.0, "Reverb Mod Phase Shift", QuadratureColor(1), MachineFlags::x_all, MachineFlags::x_all)
F(ReverbReturn, RVR, Reverb, 3, 3, 1.0, "Reverb Return", SmartGrid::Color::Fuscia, MachineFlags::x_all, MachineFlags::x_all)
F(Tempo, TMP, TheoryOfTime, 0, 0, 0.5, "Tempo", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(PLLPhaseLearn, PPL, TheoryOfTime, 0, 1, 0.5, "PLL Phase Learn", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(PLLFreqLearn, PFL, TheoryOfTime, 1, 1, 0.5, "PLL Freq Learn", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(PLLPhaseApply, PPAP, TheoryOfTime, 2, 1, 0.5, "PLL Phase Apply", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(PLLFreqApply, PFAP, TheoryOfTime, 3, 1, 0.5, "PLL Freq Apply", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(TempoLFOSkew, TLS, TheoryOfTime, 0, 2, 0.5, "Tempo LFO Skew", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(TempoLFOMult, TLM, TheoryOfTime, 1, 2, 0, "Tempo LFO Mult", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(TempoLFOShape, TLSH, TheoryOfTime, 2, 2, 0.5, "Tempo LFO Shape", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(TempoLFOCenter, TLC, TheoryOfTime, 0, 3, 0.75, "Tempo LFO Center", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(TempoLFOSlope, TLSL, TheoryOfTime, 1, 3, 0, "Tempo LFO Slope", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(TempoLFOIndex, TLIX, TheoryOfTime, 3, 3, 0, "Tempo LFO Index", SmartGrid::Color::Yellow, MachineFlags::x_all, MachineFlags::x_all)
F(MasterVolume, MVOL, Mastering, 3, 0, 1, "Master Volume", SmartGrid::Color::SeaGreen, MachineFlags::x_all, MachineFlags::x_all)
F(LowEq, LEQ, Mastering, 0, 2, 3.0 / 5.0, "Low Eq", SmartGrid::Color::SeaGreen, MachineFlags::x_all, MachineFlags::x_all)
F(LowMidEq, LME, Mastering, 1, 2, 3.0 / 5.0, "Low Mid Eq", SmartGrid::Color::SeaGreen, MachineFlags::x_all, MachineFlags::x_all)
F(HighMidEq, HME, Mastering, 2, 2, 3.0 / 5.0, "High Mid Eq", SmartGrid::Color::SeaGreen, MachineFlags::x_all, MachineFlags::x_all)
F(HighEq, HEQ, Mastering, 3, 2, 3.0 / 5.0, "High Eq", SmartGrid::Color::SeaGreen, MachineFlags::x_all, MachineFlags::x_all)
F(LowBandCutoff, LBC, Mastering, 0, 3, 0.5, "Low Band Cutoff", SmartGrid::Color::SeaGreen, MachineFlags::x_all, MachineFlags::x_all)
F(MidBandCutoff, MBC, Mastering, 1, 3, 0.5, "Mid Band Cutoff", SmartGrid::Color::SeaGreen, MachineFlags::x_all, MachineFlags::x_all)
F(HighBandCutoff, HBC, Mastering, 2, 3, 0.5, "High Band Cutoff", SmartGrid::Color::SeaGreen, MachineFlags::x_all, MachineFlags::x_all)
F(MasterGain, MST, Mastering, 3, 3, 3.0 / 5.0, "Master Gain", SmartGrid::Color::SeaGreen, MachineFlags::x_all, MachineFlags::x_all)
F(Source1HP, S1HP, Inputs, 0, 0, 0, "Source 1 HP", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source1LP, S1LP, Inputs, 0, 1, 1, "Source 1 LP", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source1Gain, S1GN, Inputs, 0, 3, 0, "Source 1 Gain", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source2HP, S2HP, Inputs, 1, 0, 0, "Source 2 HP", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source2LP, S2LP, Inputs, 1, 1, 1, "Source 2 LP", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source2Gain, S2GN, Inputs, 1, 3, 0, "Source 2 Gain", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source3HP, S3HP, Inputs, 2, 0, 0, "Source 3 HP", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source3LP, S3LP, Inputs, 2, 1, 1, "Source 3 LP", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source3Gain, S3GN, Inputs, 2, 3, 0, "Source 3 Gain", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source4HP, S4HP, Inputs, 3, 0, 0, "Source 4 HP", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source4LP, S4LP, Inputs, 3, 1, 1, "Source 4 LP", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(Source4Gain, S4GN, Inputs, 3, 3, 0, "Source 4 Gain", SmartGrid::Color::White, MachineFlags::x_all, MachineFlags::x_all)
F(DeepVocoderSlewUp, DVSU, DeepVocoder, 0, 0, 0.5, "Deep Vocoder Slew Up", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DeepVocoderSlewDown, DVSD, DeepVocoder, 1, 0, 0.5, "Deep Vocoder Slew Down", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVGainThresh1, DV1G, DeepVocoder, 0, 1, 0.5, "Deep Vocoder Gain Threshold Trio 1", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVRatio1, DV1R, DeepVocoder, 1, 1, 0.5, "Deep Vocoder Ratio Trio 1", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVSlopeDown1, DV1D, DeepVocoder, 2, 1, 0.5, "Deep Vocoder Slope Down Trio 1", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVSlopeUp1, DV1U, DeepVocoder, 3, 1, 0.5, "Deep Vocoder Slope Up Trio 1", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVGainThresh2, DV2G, DeepVocoder, 0, 2, 0.5, "Deep Vocoder Gain Threshold Trio 2", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVRatio2, DV2R, DeepVocoder, 1, 2, 0.5, "Deep Vocoder Ratio Trio 2", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVSlopeDown2, DV2D, DeepVocoder, 2, 2, 0.5, "Deep Vocoder Slope Down Trio 2", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVSlopeUp2, DV2U, DeepVocoder, 3, 2, 0.5, "Deep Vocoder Slope Up Trio 2", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVGainThresh3, DV3G, DeepVocoder, 0, 3, 0.5, "Deep Vocoder Gain Threshold Trio 3", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVRatio3, DV3R, DeepVocoder, 1, 3, 0.5, "Deep Vocoder Ratio Trio 3", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVSlopeDown3, DV3D, DeepVocoder, 2, 3, 0.5, "Deep Vocoder Slope Down Trio 3", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
F(DVSlopeUp3, DV3U, DeepVocoder, 3, 3, 0.5, "Deep Vocoder Slope Up Trio 3", SmartGrid::Color::Ocean, MachineFlags::x_all, MachineFlags::x_all)
